add gui sliders for controlling the arm
note: we get some errors on the sliders (traceback pasted below)

this is either because of bug in prebuilt arm binaries for macos or due
to sliders not registering properly with the gui

```
Traceback (most recent call last):
  File "/Users/mukund/dev/dspy-on-robot/./visualize_arm.py", line 91, in <module>
    interactive_move_to_xyz()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/mukund/dev/dspy-on-robot/.venv/lib/python3.13/site-packages/click/core.py", line 1462, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/mukund/dev/dspy-on-robot/.venv/lib/python3.13/site-packages/click/core.py", line 1383, in main
    rv = self.invoke(ctx)
  File "/Users/mukund/dev/dspy-on-robot/.venv/lib/python3.13/site-packages/click/core.py", line 1246, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mukund/dev/dspy-on-robot/.venv/lib/python3.13/site-packages/click/core.py", line 814, in invoke
    return callback(*args, **kwargs)
  File "/Users/mukund/dev/dspy-on-robot/./visualize_arm.py", line 63, in interactive_move_to_xyz
    target_z = p.readUserDebugParameter(slider_z)
pybullet.error: Failed to read parameter.
```